# Generated by Django 5.0.6 on 2024-05-17 07:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место выполнения')),
                ('time', models.DateTimeField(verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('pleasant', models.BooleanField(default=False, verbose_name='Признак приятности')),
                ('periodicity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('complete_time', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публикации')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
        ),
    ]
