# Generated by Django 5.0.6 on 2024-05-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['id'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
    ]
