# Generated by Django 5.0.6 on 2024-05-18 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='complete_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время выполнения'),
        ),
    ]
