# Generated by Django 5.0.6 on 2024-05-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_complete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата следующего действия'),
        ),
    ]
