# Generated by Django 5.0.6 on 2024-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='Время выполнения'),
        ),
    ]
